### ISSUE TITLE
Copy edit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/sensing-science#1]
@LornaLynch could you have a look over my copy please.
TIA

**Comment by LornaLynch** [comment]
sure: no problem :)

**Comment by LornaLynch** [comment]
There's some text missing at the beginning of the lesson 2 teacher's plan (under Black and silver cans), and also at line 36.

**Comment by LornaLynch** [comment]
In lesson 4 (teacher's instructions) there is text missing from the first line ("students will investigate the...")

Also at line 71 under Extension Task. 

Should there be illustrations in this document or not? There was a reference to adding illustrations under the instructions for the experiment; I removed it as superfluous but was not sure which illustrations were wanted.

**Comment by LornaLynch** [comment]
Just to check: should lessons 2 and 3 both involve black and silver cans? It seems like a lot of the material is duplicated, but I may be misunderstanding :)

**Comment by LornaLynch** [comment]
Sorry to be thick, but I can't figure out how to move .DS_Store into the Code folder in lesson 5. Can you show me? 

The same goes for lessons 6-8.

**Comment by MarcScott** [comment]
Cheers - will fix this and the push to live
