### ISSUE TITLE
Link to code.zip doesn't work

### ISSUE THREAD

**Issue by lurch** [raspberrypilearning/sensing-science#3]
When viewing the resource at https://www.raspberrypi.org/learning/sensing-science/ the "zip file here" links to https://www.raspberrypi.org/learning/code.zip which doesn't work. The link works fine when viewed via https://github.com/raspberrypilearning/sensing-science/blob/master/overview.md

Pinging @bennuttall as I suspect this might be something he'll need to look at? Possibly vaguely related to https://github.com/raspberrypilearning/networking-lessons/issues/24 (which is still open too) ?

**Comment by bennuttall** [comment]
It's working now. I guess it's been fixed?

**Comment by lurch** [comment]
Yeah, fixed in https://github.com/raspberrypilearning/sensing-science/commit/eeae5a57cf811fd2fa8f6e13760608536df3512c
(although I dunno if using an absolute URL was the best fix?)
